### ISSUE TITLE
No subtitle language files

### ISSUE THREAD

**Issue by ghost** [JamiesWhiteShirt/clothesline-fabric#10]
There appears to not be a language file setup for the subtitles of clothesline anchors squeaking. This means that when you have subtitles on, instead of a shorter message like "Clothesline anchor squeaks" when the sound plays, the text "subtitles.block.clothesline.clothesline_anchor.squeak" displays, which at "auto" GUI scale on my monitor takes up over half the screen width. 
![relevant screenshot of the broken clothesline anchor text covering up food and health bars](https://user-images.githubusercontent.com/15249812/62969592-9f52c500-bddb-11e9-97d2-56168fad21b3.png)

**Comment by ghost** [comment]
It looks like the language file has subtitles but is referencing them as 
`subtitles.block.clothesline-fabric.clothesline_anchor.squeak`
whereas in-game it shows up as 
`subtitles.block.clothesline.clothesline_anchor.squeak`
so either an easy fix in namespacing or in just editing the language file slightly.

**Comment by JamiesWhiteShirt** [comment]
Resolved in 0.1.1
