### ISSUE TITLE
Mod attempts to register channels on non fabric server

### ISSUE THREAD

**Issue by yuiidev** [JamiesWhiteShirt/clothesline-fabric#11]
The mod attempts to register a channel with the name `clothesline-fabric:remove-attachment` which is too long for (on what I've tested it anyway) Paper servers and causes the client to disconnect.

This is when running the mod on the client while connecting to a non-fabric server.

**Comment by liach** [comment]
Should be a paper bug that they don't take long channel names. Btw does clothesline register the channel properly first?

**Comment by natanfudge** [comment]
I think the bug is running a mod that needs to run on the server without it being ran on the server :)

**Comment by JamiesWhiteShirt** [comment]
Sorry, but only a few specific mods are designed to handle connecting to non-fabric servers, and Clothesline is not one of them. While it might be possible, it's really not intended. I therefore consider this issue invalid.

**Comment by yuiidev** [comment]
@liach Clothesline only registers properly when both client and server have the mod, or in this case, when I'm playing singleplayer.

@natanfudge No. The bug is that the mod is attempting to register a channel when it has no business doing so. It should do nothing, like every other mod that adds blocks etc is doing.

@JamiesWhiteShirt Not really, the issue is that you're trying to register a messaging channel at all, when the server doesn't have clothesline. Saying that there is only few mods is just false, you shouldn't just assume that the server being connected to is a Fabric server. Every other mod I'm running works perfectly fine (in the sense that they don't crash the client, the blocks obviously aren't available). So to clarify, what I'm asking is for you to write a fix so it just doesn't do anything at all when it's not on a Fabric server.

**Comment by liach** [comment]
So you are saying that clothline client will send packets like `clothline:client_feedback` (a fabricated one for example) to paper server, paper received that `minecraft:register` packet with `clothline:client_feedback` as its content and decided to kick the client for this? This is a paper bug, not a clothline one. After all, paper is full of ancient remains from almost decades ago, e.g. invalid identifiers, and keeps to fuck up modern minecraft and stuff (e.g. they even missed a lot of events during their 1.14 port)

**Comment by yuiidev** [comment]
Do you have any sources for that @liach ? I doubt that's the case when so many massive servers are running Paper servers. If that is actually the case then that's pretty interesting, and worth doing more research into.

**Comment by liach** [comment]
Guess clothline actually need to call `canServerReceive(Identifier)` in networking api before it tries to send a packet. Not really paper problem, but I just don't understand packet networking that well.

**Comment by JamiesWhiteShirt** [comment]
@Demozo I can guarantee that most mods assume that both the server and the client have the mod installed. Whether or not the assumption has any effects is depends on how the mod works. The effects may be subtle, or in this case, you've experienced a disconnection. It's not an artificial restriction - it's just an assumption that makes things easier. The real issue here might be how Fabric lacks a method to detect this scenario to avoid the issue.

I get that it's inconvenient and that the fix might be simple, but I don't want to design for this use case because I don't believe the use case actually makes sense with how mods work.

**Comment by LemmaEOF** [comment]
If you were connecting to a Fabric server instead of a Paper server, Fabric would reject your connection because of your client having blocks and items the server doesn't. *This mod is required on both client and server, just like any mod that adds blocks or items is.* There is nothing that can or should be done to fix this crash, because this is working as intended.

**Comment by yuiidev** [comment]
@JamiesWhiteShirt It does make sense though, I'm connecting to a server that does not have that mod, or just doesn't support mods at all in the first place, why does your mod still need to do it's thing? It doesn't.

@Boundarybreaker This is wrong. I've just checked this myself. I can join a Fabric server that doesn't have _any_ mods installed perfectly fine with mods that add blocks (Just Adorn in this case). This is not intended, it is never intended to disconnect a player unless their packets are incorrect or they're being kicked, and if it is intended it's bad design. Furthermore, there is something that can be done, which is what was suggested above by using some sort of `canServerReceive` method.

**Comment by LemmaEOF** [comment]
That's a bug of Fabric's end, then. It's supposed to boot you if there's registry mismatches between client and server.

**Comment by yuiidev** [comment]
Yes, if the server requires the client to have mods. Not the other way around.

Server requires A but client only has B, C? Disconnect.
Server requires A but client has A, B, C? Works fine, join.
Server requires nothing but client has A, B, C? Works fine, join.

There is no reason to disconnect a client if it fulfills the requirements of the server and more.

**Comment by liach** [comment]
Err, we are getting off topic. Nice discussion on networking, but clothesline is not a mod focused on networking.

**Comment by yuiidev** [comment]
It's not off topic at all? Their argument was that it was intended behaviour I'm explaining why it isn't.

Regardless, as this apparently won't be fixed, even though it is such a simple thing to do, I will leave it at this.
