### ISSUE TITLE
0.2.1+1.16.2 Dependency issue

### ISSUE THREAD

**Issue by ghost** [JamiesWhiteShirt/clothesline-fabric#14]
[latest.log](https://github.com/JamiesWhiteShirt/clothesline-fabric/files/5131618/latest.log)

This happens with fabric-api-0.19.0+build.398-1.16 and Fabric Loader 206.

**Comment by JamiesWhiteShirt** [comment]
You have to install Fabric API. The log suggests that you do not have fabric API installed. Check your installation.

**Comment by ghost** [comment]
You're right.  My fabric api jar was overwritten by the content of another mod.
Thanks!
