### ISSUE TITLE
Hopper Duplicating Items

### ISSUE THREAD

**Issue by A-a-ron717** [JamiesWhiteShirt/clothesline-fabric#17]
When an item travels over a hopper the item goes in AND stays on the clothesline, effectively duplicating it.

**Comment by JamiesWhiteShirt** [comment]
In my 1.16.3 development environment, I placed a clothesline anchor over a hopper, tied a clothesline to it, placed items on the clothesline and could not reproduce the issue.

I cannot resolve this issue without instructions on how to reproduce it. To best track down the issue, I need the full set of mods (preferably with their versions), the version of Minecraft used and especially the version of Clothesline used. If you can capture a screenshot of the setup that has this issue, I would like to see that as well.

**Comment by A-a-ron717** [comment]
Here's a video of what's happening: https://youtu.be/T1cWh2YlBos
I attached a txt file of the list of mods I use (I used the command console to pull the names of the jar files into a txt and I believe all of them have versions in their names)
[modlist.txt](https://github.com/JamiesWhiteShirt/clothesline-fabric/files/5361989/modlist.txt)

**Comment by JamiesWhiteShirt** [comment]
Thanks for the detailed report. I managed to reproduce the issue when installing Clothesline and LibBlockAttributes in the same environment. This could be an issue with either mod, I will investigate this.

**Comment by JamiesWhiteShirt** [comment]
Resolved in 0.3.1
