### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by The-Fireplace** [JamiesWhiteShirt/clothesline-fabric#2]
https://paste.ubuntu.com/p/XxQmmzyNWP/
Fabric-loader-0.3.7.109-19w11b.2
Clothesline-fabric-0.0.9.0-all

Let me know if you need any more info

**Comment by JamiesWhiteShirt** [comment]
This is most likely expected breakage with 19w11b. I'll have a fix ready soon.
