### ISSUE TITLE
Crash when breaking anchors

### ISSUE THREAD

**Issue by Juuxel** [JamiesWhiteShirt/clothesline-fabric#6]
Minecraft version: 1.14.3  
Clothesline version: 0.0.16  
Full log: [gist](https://gist.github.com/Juuxel/5bd33fffaedf338d6662d76d281ee9a2)

The game crashes when you break an anchor in 1.14.3. It looks like the new gamerule changes broke `ServerNetworkManager.dropItems` here:

https://github.com/JamiesWhiteShirt/clothesline-fabric/blob/2d3dd5bdf32bf233c0da9a6ec307521c566a26ae/src/main/java/com/jamieswhiteshirt/clotheslinefabric/common/impl/ServerNetworkManager.java#L57

**Comment by JamiesWhiteShirt** [comment]
Resolved in 0.1.0
