### ISSUE TITLE
Hopper interaction is finicky

### ISSUE THREAD

**Issue by AaronsCoding** [JamiesWhiteShirt/clothesline-fabric#9]
Items on the clotheslines don't interact with hoppers if it is traveling down the line going south. This really hinders it's compatibility with storage systems.

**Comment by JamiesWhiteShirt** [comment]
I am unable to reproduce the specific isse you described. Could you perhaps share with a screenshot or video? Also, in case you are unaware, the hopper interaction will only work when they insert into or pull from a clothesline anchor block. Did you perhaps try to put them directly on the line?

**Comment by AaronsCoding** [comment]
I am so sorry for wasting your time but I figured out the issue and I was just being dumb! I wasn't doing it right at first but now that I did a little bit of adjusting it works without a problem! (aside from the other issue that I opened at the same time as this one)
